apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp-deployment
  namespace: default
  labels:
    app: quizapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      containers:
      - name: quizapp
        image: amrutakedari/quizapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: PYTHONDONTWRITEBYTECODE
            value: "1"
          - name: PYTHONUNBUFFERED
            value: "1"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: quizapp-service
  namespace: default
spec:
  selector:
    app: quizapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000